language: node_js

node_js:
  - 'node'

install:
  - "npm install"

script:
  - "echo 'no script'"

cache:
  directories:
     - "./node_modules"

before_deploy:
  - "npm run build:gh-pages"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master


notifications:
  email: false